### ISSUE TITLE
Error waiting for kube-proxy and the nodes

### ISSUE THREAD

**Issue by wallrj** [Mirantis/kubeadm-dind-cluster#79] opened 2018-02-08 13:06 UTC
Downloaded dind-cluster-v1.8.sh today and tried it on a new Ubuntu 17.10 machine, but it failed.

There are errors relating to mount namespace propagation ~~so I wonder if it's caused by: https://github.com/Mirantis/kubeadm-dind-cluster/pull/75~~

(I tested with an earlier version and got the same error)

```
wget https://cdn.rawgit.com/Mirantis/kubeadm-dind-cluster/master/fixed/dind-cluster-v1.8.sh
```

```
richard@pet-instance-1:~$ ./dind-cluster-v1.8.sh up
```

Exits with:

```
* Deploying k8s dashboard                                                                                                                             
deployment "kubernetes-dashboard" created                                                                                                             
service "kubernetes-dashboard" created                                                                                                                
clusterrolebinding "add-on-cluster-admin" created                                                                                                     
* Patching kube-dns deployment to make it start faster                                                                                                
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply                                     
deployment "kube-dns" configured                                                                                                                      
* Taking snapshot of the cluster                                                                                                                      
deployment "kube-dns" scaled                                                                                                                          
deployment "kubernetes-dashboard" scaled                                                                                                              
WARNING: controller manager glitch: dns & dashboard won't stop; pods may 'blink' for some time after restore                                          
* Waiting for kube-proxy and the nodes                                                                                                                
......................................................................................................................................................
.................................................Error waiting for kube-proxy and the nodes 
```

Kubectl shows:

```
richard@pet-instance-1:~$ ~/.kubeadm-dind-cluster/kubectl get pods --all-namespaces
NAMESPACE     NAME                                  READY     STATUS             RESTARTS   AGE
kube-system   etcd-kube-master                      1/1       Running            1          10m
kube-system   kube-apiserver-kube-master            1/1       Running            1          10m
kube-system   kube-controller-manager-kube-master   1/1       Running            3          11m
kube-system   kube-proxy-5vzrx                      0/1       CrashLoopBackOff   9          10m
kube-system   kube-proxy-dxkg7                      0/1       CrashLoopBackOff   10         10m
kube-system   kube-proxy-qsfnh                      0/1       CrashLoopBackOff   10         10m
kube-system   kube-scheduler-kube-master            1/1       Running            1          10m

```

And

```
  Warning  Failed                 3m (x3 over 3m)  kubelet, kube-master  Error: failed to start container "kube-proxy": Error response from daemon: linux mounts: Path /run/xtables.lock is mounted on /run but it is not a shared or slave mount.

```

```
richard@pet-instance-1:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.10"
VERSION_ID="17.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

```

```
richard@pet-instance-1:~$ docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:14 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:47 2017
  OS/Arch:      linux/amd64
  Experimental: false

```

**Comment by wallrj** [comment] 2018-02-08 14:05
Running `docker exec kube-node-2 mount --make-shared /lib/modules` and `docker exec kube-node-2 mount --make-shared /run` on each of the nodes seems to have got kube-proxy running.

**Comment by mwpeterson** [comment] 2018-02-09 16:58
The latest update to the dind-cluster-v1.8.sh didn't fix this for me on OSX. Now there's a new error:
```
* Starting node container: 1
* Starting DIND container: kube-node-1
* Node container started: 1
* Starting node container: 2
* Starting DIND container: kube-node-2
* Node container started: 2
mount: /lib/modules is not mountpoint or bad option

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
```

**Comment by lukaszo** [comment] 2018-02-13 16:14
@wallrj I wasn't able to reproduce your issue on Ubuntu 17.10. Maybe you've got old cached version from `https://cdn.rawgit.com` and new image from docker.

@mwpeterson I don't have OSX but I will try to fix your issue by checking if the path is a mountpoint.

**Comment by lukaszo** [comment] 2018-02-14 22:14
@ivan4th can we close this one? I couldn't reproduce the first issue and the second one is fixed now.

**Comment by ivan4th** [comment] 2018-02-15 09:07
Sure, closing, thanks @lukaszo

**Closed by ivan4th** 2018-02-15 09:07 UTC

**Comment by wallrj** [comment] 2018-02-22 12:27
Sorry for not replying sooner.

> @wallrj I wasn't able to reproduce your issue on Ubuntu 17.10. Maybe you've got old cached version from https://cdn.rawgit.com and new image from docker.

I've now cleaned out all docker images and re-downloaded the script and things seem to be working on my Ubuntu 17.04 vitual machine.

Thanks for looking into it.
