### ISSUE TITLE
CentOS 7: Docker App Container Engine startup fails - error initializing graphdriver: driver not supported

### ISSUE THREAD

**Issue by pmichali** [Mirantis/kubeadm-dind-cluster#32] opened 2017-07-21 10:52 UTC
When trying to start up DinD, during kubeadm init, a failure is seen for Docker Application Container Engine, saying driver not supported.

When checking the master container, docker is not running due to this error. If an attempt is made to manually start docker, the same error is seen.

This works on Ubuntu 16.04. In comparing the two, we see that for Ubuntu the host and the master container use the "overlay2" driver. Both are running Ubuntu. For CentOS 7, the host is using "devicemapper" (overlay2 is not supported), and the master container is using "overlay2". However, the container OS is RHEL 4.8.5-11.

Is it possible that RHEL doesn't support "overlay2" driver? If not, how to force a different driver that does work?

**Comment by pmichali** [comment] 2017-07-24 15:49
Although resolved for Ubuntu, it is still a problem for CentOS.

**Comment by jellonek** [comment] 2017-07-31 08:39
On fedora you can change storage driver replacing content of `/etc/sysconfig/docker-storage` with:
```
DOCKER_STORAGE_OPTIONS="--storage-driver overlay2 "
```
Probably the same (or something similar) should work for Centos and RHEL.

**Comment by tennix** [comment] 2017-08-07 11:55
@pmichali @jellonek Hi, I've found that changing `overlay2` to `overlay` works on CentOS. Currently CentOS doesn't support overlay2 driver, so in [rundocker](https://github.com/Mirantis/kubeadm-dind-cluster/blob/master/image/rundocker#L25-L27) we can't just set it to overlay2 whenever there exists *overlay* in /proc/filesystems.
I don't have an OS that supports overlay2 driver at hand, so I don't know whether *overlay2* in /proc/filesystems when overlay2 driver is supported. Or I'd like to send a PR to fix this issue. I hope this would be solved quickly as we use this for our CI environment.

**Comment by pmichali** [comment] 2017-08-07 12:38
Can you advise on how you setup DinD to have the OS use overlay vs overlay2? I’d like to try it out when I get a chance.  BTW, Ubuntu 16.04 works with overlay2, and I’ve been using that currently.

Regards,

Paul Michali (pcm)

**Comment by pigmej** [comment] 2017-08-07 12:54
@tennix overlay2 is not listed in /proc/filesystems when it's supported. Checked on fedora

**Comment by tennix** [comment] 2017-08-07 13:38
@pmichali I built a new docker image based on mirantis/kubeadm-dind-cluster:v1.7 and changed *overlay2* in /usr/local/bin/rundocker with *overlay*. And tagged this new image as mirantis/kubeadm-dind-cluster:v1.7 and run dind up again.

@pigmej Oh, that way how can we determine whether use *overlay2* or *overlay*. Maybe we can follow docker's convention by checking kernel version. I'll send a PR if you like

**Comment by ivan4th** [comment] 2017-08-07 14:19
Hopefully fixed in 477c3e399fbcabfac0c7c3f5f0918031fff65a37, please verify.

**Comment by tennix** [comment] 2017-08-07 14:58
@ivan4th Yeah, I just tried that and it works. Thanks for your quickly fix

**Comment by pmichali** [comment] 2017-08-07 15:39
@ivan4th Thanks. I'll give it a try on CentOs 7 system, as soon as I reprovision one.

**Comment by jellonek** [comment] 2017-08-07 23:48
@tennix `overlay` and `overlay2` are 2 versions of docker "graph driver" which are using the same `overlayfs` filesystem under the hood.
For wider info please refer to https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/

**Comment by ivan4th** [comment] 2017-08-16 11:16
@pmichali did the fix work for you?

**Comment by pmichali** [comment] 2017-08-16 11:18
I checked on my lab system running CentOS7 and was able to bring up the cluster just fine. I also tried using GCE, but am having a problem with validating certs. In any case, it seems like this is working. Thanks!

**Comment by pmichali** [comment] 2017-08-16 12:35
Yes, the cluster came up fine with CentOS. I tried using gcd-setup.sh, but I’ve got some problem with certificates, and docker-machine is not communicating with GCE. I tried generating a new certificate (JSON file) and new project, but still am having issues. Not sure what I’m doing wrong, but not related to this commit. This could be closed.

Regards,

Paul Michali (pcm)

**Comment by lukaszo** [comment] 2018-04-19 18:57
Looks like the issue is fixed

**Closed by lukaszo** 2018-04-19 18:57 UTC
